INSERT INTO USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES ('tess@mail.com', 'testy', 'Tess', '2000-10-10');
INSERT INTO USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES ( 'bob@mail.com', 'bobby', 'Robert', '1990-01-01');
INSERT INTO USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES ( 'sam@mail.com', 'sammy', 'Samanta', '1980-12-12');
INSERT INTO USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES ( 'jane@mail.com', 'janny', 'Jane', '1990-11-11');
INSERT INTO USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES ( 'hhh@mail.com', 'harry', 'Harry', '1985-02-02');

INSERT INTO FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID) VALUES ('Leon', 'About killer', '1984-12-14', 110, 5);
INSERT INTO FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID) VALUES ('La-la Land', 'Love story', '2017-01-12', 120, 4);
INSERT INTO FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID) VALUES ('The Shining', 'Horror film', '1980-05-23', 150, 5);
INSERT INTO FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID) VALUES ('Frozen', 'Disney animation', '2013-12-12', 100, 1);
INSERT INTO FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID) VALUES ('Barbi', 'Pink comedy', '2023-07-09', 115, 3);

INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS) VALUES (1, 2, FALSE);
INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS) VALUES (2, 1, TRUE);
INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS) VALUES (3, 2, FALSE);
INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS) VALUES (2, 3, TRUE);
INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS) VALUES (1, 4, FALSE);
INSERT INTO FRIENDS (USER_ID, FRIEND_ID, STATUS) VALUES (4, 1, TRUE);

INSERT INTO LIKES (FILM_ID, USER_ID) VALUES (1, 2);
INSERT INTO LIKES (FILM_ID, USER_ID) VALUES (2, 4);
INSERT INTO LIKES (FILM_ID, USER_ID) VALUES (3, 5);
INSERT INTO LIKES (FILM_ID, USER_ID) VALUES (4, 1);
INSERT INTO LIKES (FILM_ID, USER_ID) VALUES (1, 4);
INSERT INTO LIKES (FILM_ID, USER_ID) VALUES (5, 1);
INSERT INTO LIKES (FILM_ID, USER_ID) VALUES (1, 5);

INSERT INTO FILM_GENRES (FILM_ID, GENRE_ID) VALUES (1, 6);
INSERT INTO FILM_GENRES (FILM_ID, GENRE_ID) VALUES (1, 2);
INSERT INTO FILM_GENRES (FILM_ID, GENRE_ID) VALUES (2, 2);
INSERT INTO FILM_GENRES (FILM_ID, GENRE_ID) VALUES (3, 4);
INSERT INTO FILM_GENRES (FILM_ID, GENRE_ID) VALUES (4, 3);
INSERT INTO FILM_GENRES (FILM_ID, GENRE_ID) VALUES (5, 1);
INSERT INTO FILM_GENRES (FILM_ID, GENRE_ID) VALUES (5, 2);


